# Generated by Django 5.2.9 on 2025-12-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintumourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemodel',
            name='LOGINID',
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='DOCTORID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='braintumourapp.doctormodel'),
        ),
    ]
