# Generated by Django 5.2.9 on 2025-12-21 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintumourapp', '0002_remove_medicinemodel_loginid_medicinemodel_doctorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='LOGINID',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='LOGINID',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='data',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='LOGINID',
        ),
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='LOGINID',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
