# Generated by Django 5.2.9 on 2025-12-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('braintumourapp', '0003_remove_appointmentmodel_loginid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='document',
            new_name='description',
        ),
    ]
