# Generated by Django 5.2.9 on 2025-12-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintumourapp', '0004_rename_document_postmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
