# Generated by Django 5.2.9 on 2025-12-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braintumourapp', '0005_patientmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.CharField(blank=True, max_length=100, null=True)),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='braintumourapp.patientmodel')),
            ],
        ),
    ]
